<a href="https://colab.research.google.com/github/hiteshpujari/Machine-Learning-/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
arr1 = np.array([11,22,33,44])
print(arr1)

[11 22 33 44]


In [ ]:
arr2=

In [12]:
arr2 = np.array([[11,22,33,44],[55,66,77,88]])
print(arr2)

[[11 22 33 44]
 [55 66 77 88]]


In [13]:
arr2.size

8

In [15]:
arr2.shape

(2, 4)

In [18]:
arr2.dtype

dtype('int64')

In [19]:
np.ones(2,2)

TypeError: ignored